package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'jvm_tests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("jvm_tests")) {
    requirements {
        add {
            matches("teamcity.agent.jvm.os.family", "Linux")
        }
    }
}
