package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Dokka'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("Dokka")
    name = "Dokka"
    url = "git@github.com:jb-assignment/dokka.git"
    branch = "master"
    authMethod = uploadedKey {
        uploadedKey = "id_allegro_open_source"
    }
}))

